#! /bin/bash

set -e

# This script checks the md5 checksum of a cache file against the hash expected based on the file path

file=$1 # File to validate, path specified relative to top of cache

echo -n "Validating $file ... "

# Skip if tmp file
if [ "${file##*.}" == "tmp" ]; then
    echo "OK"
    exit 0
fi

expected_hash=$(dt_md5_expected $file)
actual_hash=$(dt_md5_actual $file)

# Compare actual hash to expected hash

start_red="\033[31m"
end_red="\033[0m"

if [ "$expected_hash" != "$actual_hash" ]; then
   echo -e "\r$start_red Mismatch: $file         $end_red"
   echo "Expected hash: $expected_hash"
   echo "Actual hash:   $actual_hash"
   exit 1
else
   echo "OK"
   exit 0
fi
