#! /bin/bash

# This scripts clones a DVC repo and symlinks .dvc/cache to point to the shared cache on directflow
# Submodules are cloned recursively

# Parameters
repo=$1
cache_name=$2

# Variables
cache_root=/scratch/$PROJECT/dvc/cache
name=${repo%.git} # drop .git suffix
name=${name#*/}   # drop prefix up to /
cache_name=${2:-$name}

echo "Cloning $repo"
git clone $repo --recurse-submodules
cd $name
git submodule update --init --recursive

cache_dir=$cache_root/$cache_name
if [ -d $cache_dir ]; then
    echo "Using existing cache at $cache_dir"
else
    echo "Creating cache at $cache_dir"
    mkdir -p $cache_dir
    echo "Initialising cache with group-share permissions"
    dt_remote_init $cache_dir
fi
dvc cache dir --local $cache_root/$cache_name
cd -
