#! /bin/bash

# This script takes a .dir file and separates list elements with newlines rather than (just) commas
# This makes it easier to search and filter the contents via grep, etc.

dir=$1

cache=$(dvc cache dir)
version=$(dvc --version)
if [ "${version:0:1}" -gt 2 ]; then
    cache="$cache/files/md5"
fi

sed 's/}, {/}\n{/g' $cache/${dir:0:2}/${dir:2} \
    | sed 's/\[//g' \
    | sed 's/\]//g' \
    | sed 's/\({ *"md5": *"\([^"]*\)", *"relpath": *"\([^"]*\)"\)/"\3","\2"/' \
    | sed 's/}//g' \
    | sort
