#! /bin/bash

dir1=$1
dir2=$2

mkdir -p .tmp
echo "file,hash" > .tmp/a.csv
echo "file,hash" > .tmp/b.csv

dt_dir_pretty $dir1 >> .tmp/a.csv
dt_dir_pretty $dir2 >> .tmp/b.csv

daff --color --context 0 .tmp/a.csv .tmp/b.csv

rm .tmp/a.csv .tmp/b.csv
