#! /bin/bash

# This script searches a .dir file for the specified key word md5 hash

dir=$1    # .dir file to search
cache=$2  # path to cache or remote
md5=$3    # "key word" (search term)

sed 's/}, {/}\n{/g' $cache/${dir:0:2}/${dir:2} \
    | sed 's/\[//g' \
    | sed 's/\]//g' \
    | sed 's/\({ *"md5": *"\([^"]*\)", *"relpath": *"\([^"]*\)"\)/"\3","\2"/' \
    | sed 's/}//g' \
    | grep $md5 \
    | sed 's/,.*//g' \
    | sed 's/\"//g' \

if [ ${PIPESTATUS[5]} -eq 0 ]; then 
    echo $dir | sed 's|\./||g'
fi
