#! /bin/bash

export_list=$1
mod_name=$(dirname $export_list)

echo "Exporting for $mod_name"

cat $export_list | \
    while read -r target; do
        echo "Exporting $target"
        tree $mod_name/$target
        rsync -ah -progress $mod_name/$target $target
        echo 
    done
echo "You may also need to run \'dvc checkout -R\' on the following targets"
cat $mod_name/.dt_export
echo
