#!/bin/bash
# This script initializes a DVC project and sets up the necessary directories and files.
# NOTE: This script is designed to be run on a56 project on gadi.
# Usage: bash dt_init project_name

name=${PWD##*/}

# Check if the project name is provided
if [ -z "$1" ]; then
    echo "Usage: $0 project_name"
    echo "project_name not specified, using name of the current folder: $name"
fi


project_name=${1:-$name}


remote_dir="ssh://gadi-dm.nci.org.au/g/data/a56/dvc/analysis/$project_name"
cache_dir="/scratch/a56/dvc/cache/$project_name"
local_remote_dir="/g/data/a56/dvc/analysis/$project_name"
echo "Initializing DVC project for $project_name..."
echo "Remote directory: $remote_dir"
echo "Local remote directory: $local_remote_dir"
echo "Cache directory: $cache_dir"

# Check if .dvc directory exists
if [ -d ".dvc" ]; then
    echo "DVC project already initialized."
else
    # Initialize DVC project
    if dvc init; then
        echo "DVC project initialized."
        git commit -m "Initialize DVC project"
    else
    echo "Error: DVC initialization failed." >&2
    exit 1
    fi
fi

# Set up DVC remote and cache directory
# Initiate directories

echo "Setting up remote storage and cache directory..."
mkdir $local_remote_dir
mkdir $cache_dir
# Change permissions
chmod ug+rx $cache_dir
dt_remote_init $local_remote_dir

dvc remote add -d $project_name $remote_dir
dvc remote add --local "local" $local_remote_dir
dvc cache dir $cache_dir

# Checking
echo "Checking..."
echo "Project name: $project_name"
echo "Remote directory"
dvc remote list
echo "Cache directory"
dvc cache dir

# Add the DVC config file to git
git add .dvc/config

echo "Done!"
