#! /bin/bash

set -e

operation=$1; shift # push or pull

index_mirror_root=/g/data/a56/dvc/mirror
site_cache_dir=( $(dvc doctor | grep Repo.site_cache_dir) )
local_index=${site_cache_dir[1]}
hash=$(basename $local_index)
index_mirror=$index_mirror_root/repo/$hash

echo "Mirror index: $index_mirror"
echo "Local index:  $local_index"

# Make sure we are in a DVC repo
if [ ! -d .dvc ]; then
    echo "Not at top level of a DVC repo"
    exit 1
fi

# Create index mirror directory only if it doesn't exist already
if [ ! -d $index_mirror ]; then
    mkdir -p $index_mirror
    chmod g+rwx $index_mirror
fi

# Create local index directory with correct permissions only if it doesn't exist already
if [ ! -d $local_index ]; then
    mkdir -p $local_index
fi
if [ -O $local_index ]; then
    chmod g+rwx -R $local_index
else
    permissions=$(stat -c '%A' $local_index)
    if [ ${permissions:5:1} != 'w' ]; then
        echo "You don't have write access to $local_index on this node"
        echo "This directory is owned by $(stat -c '%U' $local_index)"
        echo "Ask them to change the permissions to give you write access"
        hn=$(hostname)
        echo "qsub -b y -l h=${hn%.*} chmod g+rwx -R $local_index"
    fi
fi

local_lock=$local_index/local.lock
mirror_lock=$index_mirror/mirror.lock

# Check for locks
if [ -e $local_lock ]; then
    echo "The local index is currently locked. Somebody might be updating the local index."
    echo "The mirror was locked by $(stat -c '%U' $local_index) at $(stat -c '%w' $local_index)"
    echo "Try again in a couple of minutes, or talk to the person who locked the mirror."
    echo "The lock could be leftover from a an operation that was interrupted."
    echo "If you are sure nobody else is updating the mirror then you can unlock the mirror by deleting the following file: $local_lock"
    exit 2
fi

if [ -e $mirror_lock ]; then
    echo "The mirror is currently locked. Somebody might be updating the mirror."
    echo "The mirror was locked by $(stat -c '%U' $mirror_lock) at $(stat -c '%w' $mirror_lock)"
    echo "Try again in a couple of minutes, or talk to the person who locked the mirror."
    echo "The lock could be leftover from a an operation that was interrupted."
    echo "If you are sure nobody else is updating the mirror then you can unlock the mirror by deleting the following file: $mirror_lock"
    exit 3
fi

# Lock before acting
if [ $operation == "pull" ]; then
    echo "Updating local index"
    touch $local_lock
    if [ ! -z "$(ls -A $index_mirror)" ]; then
        if rsync -ah --perms --chmod=ug+rw --checksum --omit-dir-times $@ $index_mirror/* $local_index/; then
            echo "Local index updated"
        else
            echo "Something went wrong. See error message above for details"
        fi
    fi
    rm $local_lock
elif [ $operation == "push" ]; then
    echo "Updating index mirror."
    touch $mirror_lock
    if rsync -ah --perms --chmod=ug+rw --checksum --omit-dir-times $@ $local_index/* $index_mirror/; then
        echo "Mirror updated"
    else
        echo "Something went wrong. See error message above for details"
    fi
    rm $mirror_lock
else
    echo "Uknown operation. Specify push or pull"
    echo "Usage: dt_index [push|pull] [rsync options]"
    exit 4
fi
