#! /bin/bash
set -e

# This script calculates the expected md5 checksum of a file in a DVC cache or remote
# based on the file path

file=$1 # File to process, path specified relative to top of cache or remote
if [ -L "$file" ]; then
    file=$(readlink $file)
fi

# Determine expected hash based on file path

hash1=$(basename "$(dirname $file)")
hash2=$(basename $file)
expected_hash=${hash1}${hash2}
expected_hash=${expected_hash%.*}        # Strip suffix (.dir or .dir_bk etc)

# Return result
echo $expected_hash
