#! /bin/bash

remote=$1

# Check if exactly one argument is given
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <directory>"
  exit 1
fi

# Check if the argument is a directory and exists
if [ ! -d "$remote" ]; then
  echo "Error: '$remote' is not a valid directory or does not exist."
  exit 2
fi

mkdir -p $remote/runs
mkdir -p $remote/files/md5

chmod g+w $remote
chmod g+w $remote/runs
chmod g+w $remote/files/md5

for i in {0..255}; do
    # Create directories
    dirname=$(printf "%02x" $i)
    mkdir -p $remote/$dirname
    mkdir -p $remote/files/md5/$dirname
    # Update permissions
    if [ "$(stat -c '%U' "$remote/$dirname")" = "$(whoami)" ]; then
        chmod 2775 $remote/$dirname
    fi
    if [ "$(stat -c '%U' "$remote/files/md5/$dirname")" = "$(whoami)" ]; then
        chmod 2775 $remote/files/md5/$dirname
    fi
done
