#! /bin/bash

set -e 

# Make sure DVC is available
dt_check_dvc

targets=$@
echo "Snapshot the following targets: $targets"

for target in $targets; do
    # Remove trailing slash if present
    [[ ${target} == */ ]] && target=${target::-1}
    snapshot_file=$target/.mtime_snapshot

    # Unprotect snapshot file if it exists
    [[ -f $snapshot_file ]] && dvc unprotect $snapshot_file

    # TODO: Consider checking whether existing snapshot matches current timestamps

    # Create file called `.mtime_snapshot` in the target directory
    # File consists of filename followed by timestamp (mtime), separated by a space
    find $target \
        -exec printf {}" " \; \
        -exec get_mtime {} \; \
        | pv \
        > $snapshot_file 
done
