#! /bin/bash

# This script does the following:
#   - creates a new cache under the CTP shared cache location
#   - creates all the required subdirectories from 00/ to ff/
#   - sets all subdirectories to be "group writable"

set -e

# TODO: Make root path configurable
cache_root=/scratch/$PROJECT/dvc/cache

cache_name=${1:-$(basename $PWD)}
cache_dir=$cache_root/$cache_name

# Make sure we are at top level of a DVC repo
dt_repo_check

# Create and initialise cache unless it exists already
if [ -d $cache_dir ]; then
    echo "Cache already exists at $cache_dir"
    echo "Skipping cache creation"
else
    echo "Creating cache at $cache_dir"
    mkdir -p $cache_dir
    dt_remote_init $cache_dir
fi

echo "Setting cache to $cache_dir"
dvc cache dir $cache_dir --local
