#! /bin/bash
set -ex

# This script searches the given cache/remote for the specified md5 hash
# and returns 
# - the .dir file(s) that contain that hash
# - the file name(s) as described in each .dir file
# - the .dvc file(s) _in the workspace_ that reference the .dir file

# TODO: search all of git history for matching .dvc files

md5=$1                               # the md5 hash to search for
cache=$(dvc cache dir 2> /dev/null)  # the current default cache
path=${2:-$cache}                     # allows the default cache to be overridden

dt_find_dir $path $md5 | dt_find_dvc

