#!/bin/bash

# This script accepts a .dir hash or a .dvc file as an argument 
# and retrieves the corresponding .dir file from the specified DVC remote
# The downloaded is saved in the current DVC cache. 

# Note: The third optional argument specifies the DVC version (default is 'v3').

# Usage: ./dt_get_dir <dir_hash> <remote_name>
# Example: ./dt_get_dir abcd1234 remote1

set -e

# Read arguments
target="$1"
remote_name="$2"
dvc_version=${3:-'v3'}

# Validate input
if [ "$target:-4" == ".dvc" ]; then
    if [ ! -f "$target" ]; then
        echo "Error: .dvc file '$target' does not exist."
        exit 1
    fi
    dir_hash=$(grep 'dir' "$target" | awk '{print $3}')
    if [ -z "$dir_hash" ]; then
        echo "Error: Could not find .dir hash in '$target'."
        echo "Perhaps $target tracks an individual file, not a directory?"
        exit 1
    fi
else
    dir_hash="$target"
fi
echo "Using .dir hash: $dir_hash"

# Get the DVC cache directory
dvc_cache_dir=$(dvc cache dir)

# Get the DVC remote URL
remote_url=$(dvc remote list | grep $remote_name | awk '{print $2}')

# Construct the path to the .dir file in the remote
if [ "$dvc_version" == "v2" ]; then
    dir_path="${dir_hash:0:2}/${dir_hash:2}"
elif [ "$dvc_version" == "v3" ]; then
    dir_path="files/md5/${dir_hash:0:2}/${dir_hash:2}"
else
    echo "Unsupported DVC version: $dvc_version"
    echo "Supported versions are 'v2' and 'v3'."
    exit 1
fi
echo "Fetching .dir file from: $remote_url/$dir_path"
echo "Saving to DVC cache directory: $dvc_cache_dir/$dir_path"

# Download the .dir file from the remote to the DVC cache directory
gsutil cp "$remote_url""$dir_path" "$dvc_cache_dir""$dir_path"